### ISSUE TITLE
outdated vuplus-opera-browser(opera-hbbtv) recipe

### ISSUE THREAD

**Issue by mx3L** [vu-plus/meta-vuplus#21]
I would like to ask you to update vuplus-opera-browser recipe to latest version, since you've made several updates since
http://code.vuplus.com/gitweb/?p=vuplus_openvuplus;a=commit;h=0f2591910e582914aea6abf6b14695930b8fa1d4, which corresponds to version which is currently in meta-vuplus.

Thank you

**Comment by vu-plus** [comment]
Your request is completed.

Thank you

**Comment by mx3L** [comment]
Thanks
