### ISSUE TITLE
update driver(solo4k)

### ISSUE THREAD

**Issue by Dima73** [vu-plus/meta-vuplus#22]
- Fix FCC problem(no video when returning from media playback)
 - Add proc entry for more options in hdmi color space and depth.

http://code.vuplus.com/gitweb/?p=vuplus_openvuplus_3.0;a=commit;h=87c5d86630960124d193315a2e9f0b36157c4de2

**Comment by Dima73** [comment]
Please help

**Comment by vu-plus** [comment]
latest driver updated, sorry for late.

**Comment by Dima73** [comment]
big thanks
