### ISSUE TITLE
Driver update

### ISSUE THREAD

**Issue by xesy** [vu-plus/meta-vuplus#27]
http://code.vuplus.com/gitweb/?p=vuplus_openvuplus_3.0;a=commit;h=8da8938d1e556a54b5165fe8f396ee791faf164a

http://code.vuplus.com/gitweb/?p=vuplus_openvuplus_3.0;a=commit;h=7d94d5c19ca91b7450170755345f6c27614bcf32

Please update drivers for 4k and hd stb's.

**Comment by vu-plus** [comment]
just updated.
