### ISSUE TITLE
vuplus-tuner-turbo drivers

### ISSUE THREAD

**Issue by Dima73** [vu-plus/meta-vuplus#4]
Please add vuplus-tuner-turbo drivers and blindscan util
http://www.google.ru/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&ved=0CCsQFjAB&url=http%3A%2F%2Fcode.vuplus.com%2Fgitweb%2F%3Fp%3Dvuplus_openvuplus%3Ba%3Dcommitdiff%3Bh%3D51195eb587fcc3dc1289af8680c47bda78711080&ei=raBcVdbpF8GhyAPniYCwCQ&usg=AFQjCNF_DCZaSOHxK9U8fF8NblE_hRYU8g&sig2=UKVqToH7AKtJHgwKTOmBGg

**Comment by Dima73** [comment]
Please add vuplus-tuner-turbo drivers!!!!!

**Comment by Dima73** [comment]
tnanks

**Comment by boba-l** [comment]
Please add vuplus-tuner-turbo drivers without error "Unknown symbol in module"
