### ISSUE TITLE
Error when Build  kernel vusolo2 with gcc 7 in rocko branche

### ISSUE THREAD

**Issue by vuteam** [vu-plus/meta-vuplus#46]
/build/tmp/work-shared/vusolo2/kernel-source/mm/rmap.c:529:26: warning: '__vma_address' is static but used in inline function 'vma_address' which is not static
|   unsigned long address = __vma_address(page, vma);

build/tmp/work-shared/vusolo2/kernel-source/mm/page_alloc.c: In function 'free_area_init_nodes':
build/tmp/work-shared/vusolo2/kernel-source/mm/page_alloc.c:5193:34: warning: array subscript is below array bounds [-Warray-bounds]
|     arch_zone_highest_possible_pfn[i-1];
build/tmp/work-shared/vusolo2/kernel-source/arch/mips/kernel/bmips_vec.S:233: Warning: .previous without corresponding .section; ignored

any help???

**Comment by andrea-adami** [comment]
This was solved with

https://github.com/vu-plus/meta-vuplus/commit/d95cb02b09ac9ddd20981989546dc5ba3d3bb71c#diff-02d251e092d74d895708111039057e88ec18b13fc8ba52f940d973b13d1ccbe9

Please close
A.A.
