### ISSUE TITLE
Enable nandsim module

### ISSUE THREAD

**Issue by Dima73** [vu-plus/meta-vuplus#5]
Please add enable nandsim(CONFIG_MTD_NAND_NANDSIM) module for all vu+ model.
This module in order to use with
OpenMultiboot https://github.com/oe-alliance/openmultiboot

example:
https://github.com/athoik/meta-formuler/commit/33acb77aed26f2ee0aadd6a3cdad6d89521aa760

**Comment by Ednaz** [comment]
I also ask to add the module nandsim.
I would like to use the multiboot Solo2

**Comment by danyy** [comment]
i support Dima73 to add enable nandsim(CONFIG_MTD_NAND_NANDSIM) module for all vu+ model
We hope that this help us to further mutual development
please lets work togother . i wish to enjoy that with vu+duo2 box

**Comment by spartak73** [comment]
I also ask to add the module nandsim to VU + Duo2.

**Comment by vasilich07** [comment]
I also ask to add the module nandsim to VU + Duo2.
thanks

**Comment by Firex3** [comment]
Hi,

I also ask to add the module nandsim for all VU+ models.
Personally I want to use it for/with multiboot VU+ Solo2.

Thanks.

**Comment by Dima73** [comment]
https://github.com/vu-plus/meta-vuplus/pull/6
