### ISSUE TITLE
Kodi FHD support

### ISSUE THREAD

**Issue by DimitarCC** [vu-plus/meta-vuplus#64]
Since currently all 4K models supports FHD skins i think is good if Kodi supports 1080p UI mode at least.
Also maybe Kodi 18 support will be better. We waiting long time for this but still nothing from VU+ team.

**Comment by andrea-adami** [comment]
As far as I see it is not a Vu+ issue.
The patches are in the DISTRO's repositories, you can change the gui settings there.
Please close.
A.A.
